### ISSUE TITLE
Problems with stats being accurately reported from the tenth frame.

### ISSUE THREAD

**Issue by josephroqueca** [josephroqueca/bowling-companion#128]
User comment:

> Stats do not include subsequent middle hits in tenth frame if first ball was a strike unless it is a second strike or follows a spare. Also, stats do not include pins left standing or include a tenth frame spare in stats if first ball in tenth frame was a strike. Likewise, if a double is thrown in the tenth and a headpin is punched this is not reflected in the middle hits total.

**Comment by joseph-roque** [comment]
Additional user comments:

> Middle hits following one or two strikes in the tenth frame are not reflected in the 'Middle hits' stats. Same holds true for a spare following a strike in the tenth. The spare is not reflected in the 'Spares converted' stats. In the case of a middle hit spare with a following strike in the tenth both middle hits are reflected in the stats for middle hits. In addition to these minor things, the fact that any pins left standing in the tenth after one or two strikes are not reflected in the 'Pins left on deck' stats. An example of this would be two strikes in the tenth followed by a headpin. The two strikes would be counted toward the 'Middle hits' stats but not the Headpin and the ten pins remaining out of the total possible 45 for the frame would not count toward the 'Pins left on deck' stats.
