### ISSUE TITLE
Count middle hit chances more accurately?

### ISSUE THREAD

**Issue by jbrains** [josephroqueca/bowling-companion#132]
This might be a matter of opinion, hence the question mark.

I think we should count a middle hit chance on the first ball of every "frame", including the 11th and 12th. This means, for example, that if I finish with 5/H, that should count as 1-for-2 on the middle in the 10th (and 11th) frame. Right now, it doesn't appear that the app counts middle hits and middle hit chances the same way. (I'm not sure what the app does; I haven't dug into the code.)

I'm calculating middle hit chances like this: if frame < 10, then count 1 chance; if frame == 10, then count the number of "frame pins" of 31 (all pins knocked down) in the first two balls and add 1. I think this is accurate, but I'm open to being corrected. In the case of finishing 5/H, that corresponds to frame pins of 3 (or 24), 31, 4, which counts as 2 middle hit chances.

As a point of comparison, with my 225 games, Bowling Companion counts me as 1776/2355 on the middle, but I count myself as 1818/2446, meaning that I'm counting an extra 42/91 that Bowling Companion isn't. I don't know yet how to figure out what Bowling Companion is doing differently from my formula, so I'm not sure who's right. (Maybe we're both wrong!)

I'm happy to submit a full request, if you're willing to point to where that calculation happens. (I'm still very new to the codebase.)

**Comment by joseph-roque** [comment]
I believe this is reflected in issue #128. Not sure if I'll close one of these issues since they've both got good info, and I've never had to deal with a duplicate before!

I would also take a look at cb1ac12176c8441d63291e3545262a2610b50660 to see where I changed the calculation for H + 2 as H and S + 2 as S. I believe you'll want to look at `StatsGraphFragment.LoadStatsGraphTask.compileGeneralStats`, paying attention to `totalShotsAtMiddle` and `middleHits`, as well as and `StatsListFragment.LoadStatsListTask`, paying attention to `totalShotsAtMiddle` and `statValues[fragment.mStatsGeneral][StatUtils.STAT_MIDDLE_HIT]`. These methods are kinda beastly though, because most of this app was my first real attempt at a project outside of class, and I haven't done anything to clean them up since...

**Comment by jbrains** [comment]
On Sun, May 29, 2016 at 12:32 AM, Joseph Roque <notifications@github.com>
wrote:

> I believe this is reflected in issue #128
> <https://github.com/joseph-roque/bowling-companion/issues/128>. Not sure
> if I'll close one of these issues since they've both got good info, and
> I've never had to deal with a duplicate before!
>
> I would also take a look at cb1ac12
> <https://github.com/joseph-roque/bowling-companion/commit/cb1ac12176c8441d63291e3545262a2610b50660>
> to see where I changed the calculation for H + 2 as H and S + 2 as S. I
> believe you'll want to look at
> StatsGraphFragment.LoadStatsGraphTask.compileGeneralStats, paying
> attention to totalShotsAtMiddle and middleHits, as well as and
> StatsListFragment.LoadStatsListTask, paying attention to
> totalShotsAtMiddle and
> statValues[fragment.mStatsGeneral][StatUtils.STAT_MIDDLE_HIT]. These
> methods are kinda beastly though, because most of this app was my first
> real attempt at a project outside of class, and I haven't done anything to
> clean them up since...
>
No problem. I hope you won’t mind if, when I finally dig into the code, I
start ripping it apart mostly to separate the domain stuff from the Android
stuff. The easy part will be seeing if our numbers don’t match; the tedious
part will be digging down to individual games to find the differences. Good
news: I have 230 games to pour through and have pulled my database out into
spreadsheets, making this part a little less difficult. :)

I’ll take a closer look after the Open.
-- 
J. B. (Joe) Rainsberger :: http://online-training.jbrains.ca ::
http://www.jbrains.ca ::
http://blog.thecodewhisperer.com

**Comment by jbrains** [comment]
I haven't been tracking my scores lately, but I noticed the additional feature. Thank you! It looks good!
