### ISSUE TITLE
Update MPAndroidChart dependency

### ISSUE THREAD

**Issue by josephroqueca** [josephroqueca/bowling-companion#140]
Current version in the app is `2.2.4`

Current release version is `3.0.1`

As there are a few breaking changes, the update will need to be built and tested well.

**Comment by joseph-roque** [comment]
Pushing to 3.0, so graphs can be designed better from the ground up.

**Comment by josephroqueca** [comment]
This doesn't need to be tracked as a specific issue, it'll just be the result of the new rewrite.
