### ISSUE TITLE
Allow teams of bowlers to be created

### ISSUE THREAD

**Issue by josephroqueca** [josephroqueca/bowling-companion#16]
Stats could be more easily compared, totals are added up automatically, switching between multiple bowlers will be very quick.

Change FAB on bowler screen to go to next bowler, not next frame? Right nav could open list of bowlers in team, could be reordered.

Right nav should be opened by default when series is added for a team.

**Comment by joseph-roque** [comment]
Moved up to next release as it would be a huge ease on those with one device marking multiple bowlers at once.

**Comment by joseph-roque** [comment]
Note that this has now been requested by a user (actually, it was a while ago, but I forgot to add the tag).

**Comment by joseph-roque** [comment]
Accidentally closed the issue... My bad!

**Comment by joseph-roque** [comment]
Moved to the next version, so that a release can be made in the near future, as this feature is taking longer than expected.

**Comment by joseph-roque** [comment]
Bumping again...
